name: Create tag

on:
  push:
    branch: "main"

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: sergeysova/jq-action@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - run: VERSION=$(curl --header "Authorization:Bearer ${{ secrets.ACCESS_TOKEN }}" \
                      "https://api.github.com/repos/HardBrain/test/tags" | jq -r '. | if length == 0 then "1.0" else .[0] | .name | split(".") as $version | $version[1] | tonumber + 1 | tostring | "\($version[0]).\(.)" end')
      - run: git tag "v${VERSION}"
      - run: git push origin --tags
      - run: git push origin --follow-tags